export const ACTION_TYPE = {
  INITIAL_PRODUCTS: "INITIAL_PRODUCTS",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  INC_QTY: "INC_QTY",
  DEC_QTY: "DEC_QTY",
  ADD_SAVE_LATER: "ADD_SAVE_LATER",
  REMOVE_SAVE_LATER: "REMOVE_SAVE_LATER",
};
